**Import 4 CSV file**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

movies = pd.read_csv('/content/drive/MyDrive/IMDb movies.csv')
names = pd.read_csv('/content/drive/MyDrive/IMDb names.csv')
ratings = pd.read_csv('/content/drive/MyDrive/IMDb ratings.csv')
titles = pd.read_csv('/content/drive/MyDrive/IMDb title_principals.csv')

Mounted at /content/drive

**Find All ACTION movies**

In [ ]:
with open('/content/drive/MyDrive/IMDb movies.csv') as f:
    lines = [line for line in f]

In [ ]:
lines[:10]

In [ ]:
import csv

In [ ]:
with open('/content/drive/MyDrive/IMDb movies.csv') as f:
    reader = csv.DictReader(f)
    movies = [line for line in reader]

In [ ]:
movies[:10]

In [ ]:
movies[0]['genre']

'Biography, Crime, Drama'

In [ ]:
'Action' in movies[0]['genre']

False

In [ ]:
action_movies = [movie
                 for movie in movies
                  if 'Action' in movie['genre']]

In [ ]:
action_movies[:10]

[{'imdb_title_id': 'tt0004465',
  'title': 'The Perils of Pauline',
  'original_title': 'The Perils of Pauline',
  'year': '1914',
  'date_published': '1914-03-23',
  'genre': 'Action, Adventure, Drama',
  'duration': '199',
  'country': 'USA',
  'language': 'English',
  'director': 'Louis J. Gasnier, Donald MacKenzie',
  'writer': 'Charles W. Goddard, Basil Dickey',
  'production_company': 'Pathé Frères',
  'actors': 'Pearl White, Crane Wilbur, Paul Panzer, Edward José, Francis Carlyle, Clifford Bruce, Donald MacKenzie, Jack Standing, Eleanor Woodruff, Leroy Baker, Louise Du Pre, Oscar Nye, Sam J. Ryan, Louis J. Gasnier, Joe Cuny',
  'description': "Young Pauline is left a lot of money when her wealthy uncle dies. However, her uncle's secretary has been named as her guardian until she marries, at which time she will officially take ...",
  'avg_vote': '6.4',
  'votes': '921',
  'budget': '$ 25000',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '5.0',
  'reviews_from_critics': '7.0'},
 {'imdb_title_id': 'tt0004635',
  'title': 'The Squaw Man',
  'original_title': 'The Squaw Man',
  'year': '1914',
  'date_published': '1914-02-15',
  'genre': 'Action, Drama, Romance',
  'duration': '74',
  'country': 'USA',
  'language': 'English',
  'director': 'Oscar Apfel, Cecil B. DeMille',
  'writer': 'Edwin Milton Royle, Cecil B. DeMille',
  'production_company': 'Jesse L. Lasky Feature Play Company',
  'actors': "Dustin Farnum, Monroe Salisbury, Winifred Kingston, Mrs. A.W. Filson, Haidee Fuller, Red Wing, Foster Knox, Fred Montague, 'Baby' Carmen De Rue, Fernando Gálvez, Eugene De Rue, H.R. Macy, H.L. Swisher, Michael J. Kilpatrick, Sydney Deane",
  'description': "A chivalrous British officer takes the blame for his cousin's embezzlement and journeys to the American West to start a new life on a cattle ranch.",
  'avg_vote': '5.8',
  'votes': '802',
  'budget': '$ 20000',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '8.0',
  'reviews_from_critics': '3.0'},
 {'imdb_title_id': 'tt0006206',
  'title': 'Les vampires',
  'original_title': 'Les vampires',
  'year': '1915',
  'date_published': '1915-11-13',
  'genre': 'Action, Adventure, Crime',
  'duration': '421',
  'country': 'France',
  'language': 'French',
  'director': 'Louis Feuillade',
  'writer': 'Louis Feuillade',
  'production_company': 'Société des Etablissements L. Gaumont',
  'actors': 'Musidora, Édouard Mathé, Marcel Lévesque, Jean Aymé, Fernand Herrmann, Stacia Napierkowska, Renée Carl, Suzanne Delvé, Georgette Faraboni, Jacques Feyder, Fridolin, Rita Herlor, Émile Keppens, Louise Lagrange, Suzanne Le Bret',
  'description': 'An intrepid reporter and his loyal friend battle a bizarre secret society of criminals known as The Vampires.',
  'avg_vote': '7.3',
  'votes': '3936',
  'budget': '',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '22.0',
  'reviews_from_critics': '52.0'},
 {'imdb_title_id': 'tt0006333',
  'title': '20,000 Leagues Under the Sea',
  'original_title': '20,000 Leagues Under the Sea',
  'year': '1916',
  'date_published': '1916-12-24',
  'genre': 'Action, Adventure, Sci-Fi',
  'duration': '105',
  'country': 'USA',
  'language': 'English',
  'director': 'Stuart Paton',
  'writer': 'Jules Verne',
  'production_company': 'Williamson Submarine Film Corporation',
  'actors': 'Dan Hanlon, Edna Pendleton, Curtis Benton, Allen Holubar, Matt Moore, Jane Gail, Howard Crampton, William Welsh, Lois Alexander, Wallis Clark',
  'description': 'A French professor and his daughter accompany Captain Nemo on an adventure aboard a submarine.',
  'avg_vote': '6.2',
  'votes': '1440',
  'budget': '$ 200000',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '26.0',
  'reviews_from_critics': '16.0'},
 {'imdb_title_id': 'tt0007257',
  'title': 'Reggie Mixes In',
  'original_title': 'Reggie Mixes In',
  'year': '1916',
  'date_published': '1916-06-11',
  'genre': 'Action, Comedy, Drama',
  'duration': '50',
  'country': 'USA',
  'language': 'English',
  'director': 'Christy Cabanne',
  'writer': 'Robert M. Baker, Roy Somerville',
  'production_company': 'Fine Arts Film Company',
  'actors': 'Douglas Fairbanks, Bessie Love, Joseph Singleton, William Lowery, Wilbur Higby, Frank Bennett, Allan Sears, Lillian Langdon, Alma Rubens, Alberta Lee, Tom Wilson',
  'description': 'Reggie, a wealthy young man about town, is eager for excitement, so he takes to visiting the rougher sections of the city in search of thrills. He meets and falls for a cabaret singer, but ...',
  'avg_vote': '4.8',
  'votes': '553',
  'budget': '',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '4.0',
  'reviews_from_critics': ''},
 {'imdb_title_id': 'tt0007260',
  'title': 'The Return of Draw Egan',
  'original_title': 'The Return of Draw Egan',
  'year': '1916',
  'date_published': '1916-10-15',
  'genre': 'Action, Adventure, Romance',
  'duration': '50',
  'country': 'USA',
  'language': 'English',
  'director': 'William S. Hart',
  'writer': 'C. Gardner Sullivan, C. Gardner Sullivan',
  'production_company': 'Kay-Bee Pictures',
  'actors': 'William S. Hart, Margery Wilson, Robert McKim, Louise Glaum, J.P. Lockney',
  'description': 'Outlaw leader "Draw" Egan, believed dead, turns up in the town of Yellow Dog. The townsfolk believe him to be William Blake, a strong and law-abiding man. They appoint him sheriff to rid ...',
  'avg_vote': '6.6',
  'votes': '128',
  'budget': '',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '6.0',
  'reviews_from_critics': '1.0'},
 {'imdb_title_id': 'tt0009682',
  'title': 'Tarzan of the Apes',
  'original_title': 'Tarzan of the Apes',
  'year': '1918',
  'date_published': '1918-01-27',
  'genre': 'Action, Adventure',
  'duration': '73',
  'country': 'USA',
  'language': '',
  'director': 'Scott Sidney',
  'writer': 'Edgar Rice Burroughs, Fred Miller',
  'production_company': 'National Film Corporation of America',
  'actors': 'Elmo Lincoln, Enid Markey, True Boardman, Kathleen Kirkham, George B. French, Gordon Griffith, Colin Kenny, Thomas Jefferson, Bessie Toner, Jack Wilson, Louis Morrison, Eugene Pallette, Fred L. Wilson',
  'description': "Kohn and Alice Clayton set sail for Africa. Mutineers maroon them. After his parents die, the newborn Tarzan is taken by a great Ape, Kala. Later the boy finds his father's knife and uses ...",
  'avg_vote': '5.7',
  'votes': '631',
  'budget': '',
  'usa_gross_income': '$ 3270000',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '13.0',
  'reviews_from_critics': '16.0'},
 {'imdb_title_id': 'tt0009894',
  'title': 'El automóvil gris',
  'original_title': 'El automóvil gris',
  'year': '1919',
  'date_published': '1919-12-11',
  'genre': 'Action, Crime',
  'duration': '223',
  'country': 'Mexico',
  'language': 'Spanish',
  'director': 'Enrique Rosas',
  'writer': 'Juan Manuel Cabrera, Miguel Necoechea',
  'production_company': 'Azteca Films',
  'actors': 'Joaquín Coss, Juan de Homs, Manuel de los Ríos, María Teresa Montoya, Dora Vila, Valentín Asperó, Juan Manuel Cabrera, Enrique Cantalaúba, Russo Conde, Ángel Esquivel, Francisco Ferriz, María Mercedes Ferriz, Miguel Ángel Ferriz, Ernesto Finance, Antonio Galé',
  'description': "A gang terrorizes Mexico City's high society on 1915. Murder, kidnaping and robbery are their trademarks. One police inspector (Cabrera) follows the gang crimes and eventually send them to ...",
  'avg_vote': '7.1',
  'votes': '149',
  'budget': '',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '1.0',
  'reviews_from_critics': '2.0'},
 {'imdb_title_id': 'tt0010879',
  'title': 'When the Clouds Roll by',
  'original_title': 'When the Clouds Roll by',
  'year': '1919',
  'date_published': '1919-12-28',
  'genre': 'Action, Comedy, Romance',
  'duration': '85',
  'country': 'USA',
  'language': 'English',
  'director': 'Victor Fleming',
  'writer': 'Thomas J. Geraghty',
  'production_company': 'Douglas Fairbanks Pictures',
  'actors': 'Douglas Fairbanks, Albert MacQuarrie, Kathleen Clifford, Frank Campeau, Ralph Lewis, Herbert Grimwood, Daisy Jefferson, Bull Montana, Victor Fleming, Thomas J. Geraghty, William C. McGann, Harris Thorpe',
  'description': 'Psychiatrist Dr. Ulrich Metz attempts to drive Daniel Brown to suicide.',
  'avg_vote': '6.9',
  'votes': '741',
  'budget': '',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '8.0',
  'reviews_from_critics': '6.0'},
 {'imdb_title_id': 'tt0011387',
  'title': 'The Last of the Mohicans',
  'original_title': 'The Last of the Mohicans',
  'year': '1920',
  'date_published': '1920-11-21',
  'genre': 'Action, Adventure, Drama',
  'duration': '73',
  'country': 'USA',
  'language': 'English',
  'director': 'Clarence Brown, Maurice Tourneur',
  'writer': 'James Fenimore Cooper, Robert Dillon',
  'production_company': 'Maurice Tourneur Productions',
  'actors': 'Wallace Beery, Barbara Bedford, Alan Roscoe, Lillian Hall, Henry Woodward, James Gordon, George Hackathorne, Nelson McDowell, Harry Lorraine, Theodore Lorch, Jack McDonald, Sydney Deane, Joseph Singleton',
  'description': 'As Alice and Cora Munro attempt to find their father, a British officer in the French and Indian War, they are set upon by French soldiers and their cohorts, Huron tribesmen led by the evil...',
  'avg_vote': '6.7',
  'votes': '1051',
  'budget': '',
  'usa_gross_income': '',
  'worlwide_gross_income': '',
  'metascore': '',
  'reviews_from_users': '26.0',
  'reviews_from_critics': '5.0'}]

In [ ]:
len(action_movies)

12106

In [ ]:
len(movies)

81273

**Looking for Actor/Actress  who have starred in ACTION movies**

In [ ]:
with open('/content/drive/MyDrive/IMDb title_principals.csv') as f:
    reader = csv.DictReader(f)
    title_principals = [line for line in reader]

In [ ]:
action_movies_ids = [movie['imdb_title_id']
                     for movie in action_movies]
action_movies_ids[:10]

['tt0004465',
 'tt0004635',
 'tt0006206',
 'tt0006333',
 'tt0007257',
 'tt0007260',
 'tt0009682',
 'tt0009894',
 'tt0010879',
 'tt0011387']

In [ ]:
action_movies_ids = set(action_movies_ids)
action_stars = [people['imdb_name_id']
                for people in title_principals
                if people['imdb_title_id'] in action_movies_ids
                and people['category'] in ['actor','actress']]
action_stars[:10]

['nm0267914',
 'nm0758457',
 'nm0455612',
 'nm0277317',
 'nm0615736',
 'nm0559013',
 'nm0529695',
 'nm0043923',
 'nm0380742',
 'nm0621051']

In [ ]:
len(action_stars)

24397

In [ ]:
len(set(action_stars))

14912

In [ ]:
with open('/content/drive/MyDrive/IMDb names.csv') as f:
    reader = csv.DictReader(f)
    names = [line for line in reader]

In [ ]:
name_list = [people['name'] for people in names if people['imdb_name_id'] in action_stars]

KeyboardInterrupt:

In [ ]:
name_list[:10]

['Lauren Bacall',
 'Humphrey Bogart',
 'Marlon Brando',
 'Richard Burton',
 'James Cagney',
 'Gary Cooper',
 'Olivia de Havilland',
 'Marlene Dietrich',
 'Kirk Douglas',
 'Henry Fonda']

In [ ]:
len(name_list)

14912

In [ ]:
len(set(name_list))

14885

**PANDAS**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/IMDb movies.csv')
df[['imdb_title_id' , 'genre']]

      imdb_title_id                      genre
0         tt0000574    Biography, Crime, Drama
1         tt0001892                      Drama
2         tt0002101             Drama, History
3         tt0002130  Adventure, Drama, Fantasy
4         tt0002199           Biography, Drama
...             ...                        ...
81268     tt9903716           Horror, Thriller
81269     tt9905412                      Drama
81270     tt9905462                      Drama
81271     tt9911774                      Drama
81272     tt9914286              Drama, Family

[81273 rows x 2 columns]

In [ ]:
df[df['genre'].apply(lambda member : 'Action' in member)]

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
35,tt0004465,The Perils of Pauline,The Perils of Pauline,1914,1914-03-23,"Action, Adventure, Drama",199,USA,English,"Louis J. Gasnier, Donald MacKenzie",...,"Pearl White, Crane Wilbur, Paul Panzer, Edward...",Young Pauline is left a lot of money when her ...,6.4,921,$ 25000,NaN,NaN,NaN,5.0,7.0
36,tt0004635,The Squaw Man,The Squaw Man,1914,1914-02-15,"Action, Drama, Romance",74,USA,English,"Oscar Apfel, Cecil B. DeMille",...,"Dustin Farnum, Monroe Salisbury, Winifred King...",A chivalrous British officer takes the blame f...,5.8,802,$ 20000,NaN,NaN,NaN,8.0,3.0
58,tt0006206,Les vampires,Les vampires,1915,1915-11-13,"Action, Adventure, Crime",421,France,French,Louis Feuillade,...,"Musidora, Édouard Mathé, Marcel Lévesque, Jean...",An intrepid reporter and his loyal friend batt...,7.3,3936,NaN,NaN,NaN,NaN,22.0,52.0
60,tt0006333,"20,000 Leagues Under the Sea","20,000 Leagues Under the Sea",1916,1916-12-24,"Action, Adventure, Sci-Fi",105,USA,English,Stuart Paton,...,"Dan Hanlon, Edna Pendleton, Curtis Benton, All...",A French professor and his daughter accompany ...,6.2,1440,$ 200000,NaN,NaN,NaN,26.0,16.0
77,tt0007257,Reggie Mixes In,Reggie Mixes In,1916,1916-06-11,"Action, Comedy, Drama",50,USA,English,Christy Cabanne,...,"Douglas Fairbanks, Bessie Love, Joseph Singlet...","Reggie, a wealthy young man about town, is eag...",4.8,553,NaN,NaN,NaN,NaN,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81232,tt9795368,Tobol,Tobol,2019,2019-02-21,"Action, Drama, History",108,Russia,Russian,Igor Zaytsev,...,"Andrey Burkovskiy, Erkebulan Dairov, Evgeniy D...","A young officer, Ivan Demarin, is sent to the ...",5.0,299,NaN,NaN,$ 2178525,NaN,2.0,NaN
81233,tt9799984,Falaknuma Das,Falaknuma Das,2019,2019-05-31,"Action, Thriller",145,India,Telugu,Vishwaksen Naidu,...,"Aakash, Ajay, Sunjit Akkinepalli, Master Aman,...",Set in the backdrop of the colonies of falaknu...,6.3,425,NaN,NaN,NaN,NaN,11.0,3.0
81239,tt9815714,The Hard Way,The Hard Way,2019,2019-03-05,Action,92,USA,English,Keoni Waxman,...,"Michael Jai White, Luke Goss, Randy Couture, M...",After learning his brother died on a mission i...,4.8,1734,$ 3000000,NaN,NaN,NaN,33.0,11.0
81248,tt9839040,Murphy's Law: Ghanoone Morfi,Murphy's Law: Ghanoone Morfi,2019,2019-01-02,"Action, Comedy, Fantasy",98,Iran,Persian,Rambod Javan,...,"Amir Jadidi, Amir Jafari, Rambod Javan, Danial...",Bahman's daughter is kidnapped. Farokh recentl...,3.6,262,IRR 35000000000,NaN,NaN,NaN,4.0,24.0
81267,tt9900782,Kaithi,Kaithi,2019,2019-10-25,"Action, Thriller",145,India,Tamil,Lokesh Kanagaraj,...,"Karthi, Narain, Dheena, George Maryan, Ramana,...","A drug bust, an injured cop and a convicted cr...",8.9,3082,$ 6000000,NaN,$ 420126,NaN,98.0,6.0

**Find the number of Action squares with MERGE**

In [ ]:
movies_df = pd.read_csv('/content/drive/MyDrive/IMDb movies.csv')
action_movie_df = movies_df[movies_df['genre']
                            .apply(lambda m : 'Action' in m)]

In [ ]:
title_principals_df = pd.read_csv('/content/drive/MyDrive/IMDb title_principals.csv')
title_principals_df.head()

  imdb_title_id  ordering imdb_name_id  category  job         characters
0     tt0000574         1    nm0846887   actress  NaN     ["Kate Kelly"]
1     tt0000574         2    nm0846894     actor  NaN  ["School Master"]
2     tt0000574         3    nm3002376     actor  NaN     ["Steve Hart"]
3     tt0000574         4    nm0170118   actress  NaN                NaN
4     tt0000574         5    nm0846879  director  NaN                NaN

In [ ]:
merged_df = action_movie_df.merge(title_principals_df,
                      how='inner' ,
                      left_on = 'imdb_title_id' ,
                      right_on = 'imdb_title_id')

In [ ]:
action_star_df = merged_df[merged_df['category'].isin(['actor','actress'])]

In [ ]:
names_df = pd.read_csv('/content/drive/MyDrive/IMDb names.csv')
action_star_df.merge(names_df ,
                     how = 'inner' ,
                     left_on = 'imdb_name_id' ,
                     right_on = 'imdb_name_id')[
                         ['imdb_name_id','name']
                         ].drop_duplicates()

      imdb_name_id                 name
0        nm0267914        Dustin Farnum
1        nm0758457     Monroe Salisbury
2        nm0455612    Winifred Kingston
3        nm0277317     Mrs. A.W. Filson
4        nm0615736             Musidora
...            ...                  ...
24391    nm1914593      Evgeniy Dyatlov
24392    nm1282927      Dmitriy Dyuzhev
24394    nm2201406          Amir Jafari
24395    nm2202538         Rambod Javan
24396   nm10521233  Danial Ghaffarzadeh

[14912 rows x 2 columns]

**Find the most POPULAR Show**

In [ ]:
movies_df = pd.read_csv('/content/drive/MyDrive/IMDb movies.csv')
movies_df.describe()

,year,duration,avg_vote,votes,metascore,reviews_from_users,reviews_from_critics
count,81273.000000,81273.000000,81273.000000,8.127300e+04,12722.000000,74196.000000,70286.000000
mean,1993.007210,100.565981,5.926587,9.421771e+03,55.762695,43.753194,27.992758
std,23.992284,25.320189,1.243315,5.220245e+04,17.757453,159.903568,58.708764
min,1906.000000,40.000000,1.000000,9.900000e+01,1.000000,1.000000,1.000000
25%,1979.000000,88.000000,5.200000,2.060000e+02,43.000000,4.000000,3.000000
50%,2002.000000,96.000000,6.100000,4.950000e+02,56.000000,9.000000,8.000000
75%,2012.000000,108.000000,6.800000,1.865000e+03,69.000000,26.000000,24.000000
max,2019.000000,3360.000000,10.000000,2.159628e+06,100.000000,8302.000000,987.000000

In [ ]:
movies_df['genre'].apply(lambda m: m.split(', ')).explode().unique()

array(['Biography', 'Crime', 'Drama', 'History', 'Adventure', 'Fantasy',
       'Romance', 'War', 'Mystery', 'Horror', 'Western', 'Comedy',
       'Family', 'Action', 'Sci-Fi', 'Thriller', 'Sport', 'Animation',
       'Musical', 'Music', 'Film-Noir', 'Adult', 'Documentary',
       'Reality-TV', 'Game-Show', 'News'], dtype=object)

In [ ]:
movies_df['genre'] = movies_df['genre'].apply(lambda m: m.split(', '))

movies_df = movies_df.explode('genre')

movies_df.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,Biography,70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,537,$ 2250,NaN,NaN,NaN,7.0,7.0
0,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,Crime,70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,537,$ 2250,NaN,NaN,NaN,7.0,7.0
0,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,Drama,70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,537,$ 2250,NaN,NaN,NaN,7.0,7.0
1,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.9,171,NaN,NaN,NaN,NaN,4.0,2.0
2,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,Drama,100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,420,$ 45000,NaN,NaN,NaN,24.0,3.0

**GROUP by Genre**

In [ ]:
movies_df.groupby('genre')[
    'votes'].sum().nlargest(5)

genre
Drama        383272842
Action       238759511
Comedy       229184548
Adventure    201525136
Crime        141155839
Name: votes, dtype: int64

In [ ]:
movies_df.groupby('genre')[
    'votes'].sum().nsmallest(5)

genre
News             213
Reality-TV       314
Documentary      478
Game-Show       3582
Adult          33077
Name: votes, dtype: int64

In [ ]:
movies_df.groupby('genre')['votes'].mean().nlargest(5)

genre
Sci-Fi       29118.408751
Adventure    28455.963852
Animation    21836.273132
Fantasy      21650.532648
Biography    21290.383736
Name: votes, dtype: float64

In [ ]:
movies_df.groupby('genre')['votes'].count().nlargest(5)

genre
Drama       44404
Comedy      27873
Romance     13379
Action      12106
Thriller    10814
Name: votes, dtype: int64

***Pivot***

**Filter Data by YEAR**

In [ ]:
movies_df = pd.read_csv('/content/drive/MyDrive/IMDb movies.csv',
                        dtype = {'year' : int})

In [ ]:
new_movies_df = movies_df[movies_df['year'] >= 2015]
new_movies_df.head(5)

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
15090,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,2018-11-02,Drama,122,"France, Iran, USA","English, German",Orson Welles,...,"John Huston, Oja Kodar, Peter Bogdanovich, Sus...",A Hollywood director emerges from semi-exile w...,6.9,5014,NaN,NaN,NaN,78.0,70.0,88.0
20324,tt0085953,Mo tai,Mo tai,2019,2019-10-22,Horror,84,Hong Kong,Cantonese,Hung-Chuen Lau,...,"Eddie Chan, Yung-Chang Chin, Pak-Kwong Ho, Men...",A woman becomes possessed and dies after a mon...,6.2,262,NaN,NaN,NaN,NaN,16.0,14.0
24705,tt0100275,La Telenovela Errante,La Telenovela Errante,2017,2018-09-06,"Comedy, Drama, Fantasy",80,Chile,Spanish,"Raoul Ruiz, Valeria Sarmiento",...,"Luis Alarcón, Patricia Rivadeneira, Francisco ...",The film revolves around the concept of soap o...,6.6,121,NaN,$ 3624,$ 3624,NaN,NaN,26.0
31606,tt0137204,Joe Finds Grace,Joe Finds Grace,2017,2017-04-22,"Animation, Adventure, Comedy",83,Canada,English,Anthony Harrison,...,"Anthony Harrison, C. Ernst Harth, Ellie Harvie...",Simple-minded Joseph Briteman breaks a golden ...,8.6,264,NaN,NaN,NaN,NaN,2.0,NaN
40529,tt0315642,Wazir,Wazir,2016,2016-01-08,"Action, Crime, Drama",103,India,Hindi,Bejoy Nambiar,...,"Amitabh Bachchan, Farhan Akhtar, Aditi Rao Hyd...",A grief-stricken cop and an amputee grandmaste...,7.1,15911,NaN,$ 1124045,$ 5633588,NaN,103.0,29.0

**Choose the most PROFITABLE Data**

In [ ]:
filtered_movies_df = new_movies_df[new_movies_df['budget'].notna() &
              new_movies_df['worlwide_gross_income'].notna()
              ][
                  ['imdb_title_id',
                   'budget',
                   'worlwide_gross_income'
                  ]
              ]

In [ ]:
filtered_movies_df['worlwide_gross_income'].apply(lambda m : m.split()[0]).unique()

array(['$'], dtype=object)

In [ ]:
filtered_movies_df['budget'].apply(lambda m : m.split()[0]).unique()

array(['$'], dtype=object)

In [ ]:
filtered_movies_df = filtered_movies_df[
    filtered_movies_df['budget'].str.slice(stop=1) == '$']

In [ ]:
filtered_movies_df['profit'] = filtered_movies_df['worlwide_gross_income'].apply(lambda m : int(m.split()[1])) - filtered_movies_df['budget'].apply(lambda m : int(m.split()[1]))
filtered_movies_df

      imdb_title_id       budget worlwide_gross_income      profit
42553     tt0369610  $ 150000000          $ 1670400637  1520400637
43345     tt0385887   $ 26000000             $ 9205026   -16794974
45409     tt0437086  $ 170000000           $ 404852543   234852543
45818     tt0448115  $ 100000000           $ 364571656   264571656
45978     tt0451279  $ 149000000           $ 821847012   672847012
...             ...          ...                   ...         ...
80946     tt9134216   $ 29900000            $ 21788746    -8111254
80974     tt9176136     $ 986000               $ 36721     -949279
81059     tt9354944    $ 5000000             $ 7257918     2257918
81234     tt9799992    $ 1200000              $ 171229    -1028771
81267     tt9900782    $ 6000000              $ 420126    -5579874

[1327 rows x 4 columns]

In [ ]:
selected_ids = filtered_movies_df[filtered_movies_df['profit'] > 0 ]['imdb_title_id']
selected_ids

42553    tt0369610
45409    tt0437086
45818    tt0448115
45978    tt0451279
47057    tt0475290
           ...
80739    tt8866064
80858    tt9024106
80869    tt9034290
80872    tt9037222
81059    tt9354944
Name: imdb_title_id, Length: 724, dtype: object

**Find AUDIENCE Group**

In [ ]:
popular_movie_df = movies_df.merge(selected_ids)
popular_movie_df['genre'] = popular_movie_df['genre'].apply(lambda m: m.split(', '))
popular_movie_df = popular_movie_df.explode('genre')
popular_movie_df.groupby('genre')['votes'].sum()

genre
Action       35613101
Adventure    32953094
Animation     5274024
Biography     6979346
Comedy       19118624
Crime         8876542
Drama        28520859
Family        3050771
Fantasy       7765014
History       2747680
Horror        6937687
Music         1712528
Musical        524983
Mystery       6358015
Romance       3884439
Sci-Fi       15447500
Sport          800577
Thriller     10948154
War            134425
Western        172758
Name: votes, dtype: int64

In [ ]:
ratings_df = pd.read_csv('/content/drive/MyDrive/IMDb ratings.csv')
ratings_df.columns

Index(['imdb_title_id', 'weighted_average_vote', 'total_votes', 'mean_vote',
       'median_vote', 'votes_10', 'votes_9', 'votes_8', 'votes_7', 'votes_6',
       'votes_5', 'votes_4', 'votes_3', 'votes_2', 'votes_1',
       'allgenders_0age_avg_vote', 'allgenders_0age_votes',
       'allgenders_18age_avg_vote', 'allgenders_18age_votes',
       'allgenders_30age_avg_vote', 'allgenders_30age_votes',
       'allgenders_45age_avg_vote', 'allgenders_45age_votes',
       'males_allages_avg_vote', 'males_allages_votes', 'males_0age_avg_vote',
       'males_0age_votes', 'males_18age_avg_vote', 'males_18age_votes',
       'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote',
       'males_45age_votes', 'females_allages_avg_vote',
       'females_allages_votes', 'females_0age_avg_vote', 'females_0age_votes',
       'females_18age_avg_vote', 'females_18age_votes',
       'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes'],
      dtype='object')

In [ ]:
ratings_df.merge(selected_ids, on = 'imdb_title_id').describe()

,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,votes_5,...,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
count,724.000000,724.000000,724.000000,724.000000,724.000000,724.000000,724.000000,724.000000,724.000000,724.000000,...,724.000000,724.000000,720.000000,720.000000,724.000000,724.000000,724.000000,724.000000,724.000000,724.000000
mean,6.380110,97085.270718,6.569613,6.673343,10949.379834,11553.534530,21536.839779,23220.102210,14516.750000,7020.233425,...,6.511326,5067.146409,6.620833,1237.163889,5.700691,285.111878,6.415193,11693.458564,6.261050,38680.546961
std,0.998099,132622.195890,0.936970,1.099790,24693.780563,25740.211939,36987.049722,30034.709758,16047.211869,7930.048325,...,0.934173,6186.956707,0.998808,1386.555961,1.054536,187.762217,1.047260,15179.420994,1.008814,50386.828281
min,2.000000,102.000000,2.500000,1.000000,10.000000,0.000000,3.000000,1.000000,2.000000,3.000000,...,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.500000,1.000000,2.200000,32.000000
25%,5.800000,11744.500000,6.000000,6.000000,1007.250000,527.000000,1215.250000,2013.250000,1943.500000,1086.000000,...,5.975000,620.000000,6.100000,241.750000,5.000000,128.000000,5.800000,1758.250000,5.600000,4490.000000
50%,6.450000,46824.500000,6.700000,7.000000,3359.000000,2422.500000,6281.000000,11114.000000,9293.500000,4445.000000,...,6.500000,2909.500000,6.700000,797.000000,5.700000,273.500000,6.500000,6438.000000,6.300000,19334.000000
75%,7.100000,120999.500000,7.200000,7.000000,9142.250000,9244.000000,24110.250000,32188.500000,21993.500000,10303.250000,...,7.200000,6900.750000,7.300000,1725.750000,6.400000,411.750000,7.200000,15147.500000,7.000000,51919.500000
max,8.900000,845841.000000,9.300000,10.000000,263109.000000,192560.000000,252525.000000,186684.000000,112920.000000,72485.000000,...,9.400000,35699.000000,10.000000,8355.000000,10.000000,801.000000,9.500000,99635.000000,8.700000,314151.000000

In [ ]:
ratings_df.merge(selected_ids, on = 'imdb_title_id').sum()

imdb_title_id                tt0369610tt0437086tt0448115tt0451279tt0475290t...
weighted_average_vote                                                   4619.2
total_votes                                                           70289736
mean_vote                                                               4756.4
median_vote                                                             4831.5
votes_10                                                               7927351
votes_9                                                                8364759
votes_8                                                               15592672
votes_7                                                               16811354
votes_6                                                               10510127
votes_5                                                                5082649
votes_4                                                                2333753
votes_3                                                                1297038
votes_2                                                                 823083
votes_1                                                                1546950
allgenders_0age_avg_vote                                                4522.5
allgenders_0age_votes                                                 153832.0
allgenders_18age_avg_vote                                               4674.7
allgenders_18age_votes                                              18558713.0
allgenders_30age_avg_vote                                               4543.7
allgenders_30age_votes                                              22657715.0
allgenders_45age_avg_vote                                               4557.2
allgenders_45age_votes                                               5651048.0
males_allages_avg_vote                                                  4557.7
males_allages_votes                                                 41327877.0
males_0age_avg_vote                                                     4339.2
males_0age_votes                                                      103887.0
males_18age_avg_vote                                                    4618.7
males_18age_votes                                                   14013357.0
males_30age_avg_vote                                                    4501.8
males_30age_votes                                                   18583645.0
males_45age_avg_vote                                                    4520.4
males_45age_votes                                                    4639255.0
females_allages_avg_vote                                                4783.6
females_allages_votes                                                9713399.0
females_0age_avg_vote                                                   4488.2
females_0age_votes                                                     29345.0
females_18age_avg_vote                                                  4805.3
females_18age_votes                                                  4074213.0
females_30age_avg_vote                                                  4714.2
females_30age_votes                                                  3668614.0
females_45age_avg_vote                                                  4767.0
females_45age_votes                                                   890758.0
top1000_voters_rating                                                   4127.3
top1000_voters_votes                                                  206421.0
us_voters_rating                                                        4644.6
us_voters_votes                                                      8466064.0
non_us_voters_rating                                                    4533.0
non_us_voters_votes                                                 28004716.0
dtype: object